import pandas as pd
import numpy as np

# FUNCTION TO RETURN DF WITH ONLY MISSING VALUES

# FUNCTION TO RANDOMLY SELECT INSTANCES WHICH HAVE ALL THEIR VALUES 

# FUCNTION TO FILL NA'S WITH A SPECIFIC VALUE

